"""employes_id nullable = true in vehicle logs

Revision ID: 09cfef5a805d
Revises: efe0a1ac48a3
Create Date: 2026-06-02 12:31:25.347518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cfef5a805d'
down_revision: Union[str, Sequence[str], None] = 'efe0a1ac48a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
