"""columns added in vehicles table

Revision ID: 104fea418545
Revises: a9cdd13a2ba4
Create Date: 2026-06-03 20:11:16.836210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104fea418545'
down_revision: Union[str, Sequence[str], None] = 'a9cdd13a2ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_odometer', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('maintenance_interval', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('maintenance_kms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'maintenance_kms')
    op.drop_column('vehicles', 'maintenance_interval')
    op.drop_column('vehicles', 'current_odometer')
    # ### end Alembic commands ###
