"""Maintenance_schedule table is added

Revision ID: 1358e53ffb2b
Revises: 
Create Date: 2026-06-01 20:12:05.012656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1358e53ffb2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripdetails', sa.Column('checkedout_time', sa.DateTime(), nullable=False))
    op.add_column('tripdetails', sa.Column('checkedin_time', sa.DateTime(), nullable=False))
    op.drop_column('tripdetails', 'checkin_time')
    op.drop_column('tripdetails', 'checkout_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripdetails', sa.Column('checkout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tripdetails', sa.Column('checkin_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tripdetails', 'checkedin_time')
    op.drop_column('tripdetails', 'checkedout_time')
    # ### end Alembic commands ###
