"""check sync

Revision ID: 1fa0bdc73669
Revises: 55b6d1f3b06e
Create Date: 2026-06-02 21:19:17.539369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa0bdc73669'
down_revision: Union[str, Sequence[str], None] = '5b3534043043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triplogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('trip_details_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('t_action', sa.Enum('OVERDUE', 'CHECKED_OUT', 'CHECKED_IN', 'CANCELLATION', name='trip_action'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['vehiclereservations.id'], ),
    sa.ForeignKeyConstraint(['trip_details_id'], ['tripdetails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triplogs')
    # ### end Alembic commands ###
