"""ending trip details ccan be null but should have validations

Revision ID: 2105d73a19ee
Revises: 42b74d25a7ab
Create Date: 2026-06-02 21:59:25.305296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2105d73a19ee'
down_revision: Union[str, Sequence[str], None] = '42b74d25a7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triplogs')
    op.alter_column('tripdetails', 'end_odometer',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tripdetails', 'end_fuel',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tripdetails', 'checkedin_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tripdetails', 'checkedin_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tripdetails', 'end_fuel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tripdetails', 'end_odometer',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('triplogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trip_details_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('t_action', postgresql.ENUM('OVERDUE', 'CHECKED_OUT', 'CHECKED_IN', 'CANCELLATION', name='trip_action'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['vehiclereservations.id'], name=op.f('triplogs_reservation_id_fkey')),
    sa.ForeignKeyConstraint(['trip_details_id'], ['tripdetails.id'], name=op.f('triplogs_trip_details_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('triplogs_pkey'))
    )
    # ### end Alembic commands ###
