"""employee table has aadharcard column

Revision ID: 52c27f6f738d
Revises: 1358e53ffb2b
Create Date: 2026-06-02 07:33:46.245912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c27f6f738d'
down_revision: Union[str, Sequence[str], None] = '1358e53ffb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('aadhar_card', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['aadhar_card'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'aadhar_card')
    # ### end Alembic commands ###
