"""reservation_end can be null

Revision ID: 5b3534043043
Revises: 00187dae9cf4
Create Date: 2026-06-02 17:20:56.573548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b3534043043'
down_revision: Union[str, Sequence[str], None] = '00187dae9cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehiclereservations', 'reservation_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'),
               nullable=True)
    op.alter_column('vehiclereservations', 'reservation_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
