"""Vehicle number added to vehicles table

Revision ID: 976d7a2c4f3b
Revises: 52c27f6f738d
Create Date: 2026-06-02 09:03:38.277394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976d7a2c4f3b'
down_revision: Union[str, Sequence[str], None] = '52c27f6f738d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'aadhar_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vehicles', sa.Column('vehicle_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'vehicles', ['vehicle_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'vehicle_number')
    op.alter_column('employees', 'aadhar_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
