"""trip details updated

Revision ID: a9cdd13a2ba4
Revises: d1b2e035b30c
Create Date: 2026-06-03 13:13:30.824139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9cdd13a2ba4'
down_revision: Union[str, Sequence[str], None] = 'd1b2e035b30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripdetails', sa.Column('actual_return_date', sa.DateTime(), nullable=True))
    op.drop_column('tripdetails', 'actual_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripdetails', sa.Column('actual_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tripdetails', 'actual_return_date')
    # ### end Alembic commands ###
