"""vehicle status added to vehicle

Revision ID: b8bf30a3db7f
Revises: 976d7a2c4f3b
Create Date: 2026-06-02 11:58:16.584720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bf30a3db7f'
down_revision: Union[str, Sequence[str], None] = '976d7a2c4f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'IN_USE', 'MAINTENANCE', 'OVERDUE', 'OUT_OF_SERVICE', name='vehicle_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'status')
    # ### end Alembic commands ###
