"""columns updated in vehicles table

Revision ID: be95ed02b8f0
Revises: 104fea418545
Create Date: 2026-06-03 20:15:53.010953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be95ed02b8f0'
down_revision: Union[str, Sequence[str], None] = '104fea418545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'maintenance_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vehicles', 'maintenance_kms',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'maintenance_kms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vehicles', 'maintenance_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
