"""end time and start time of trip is added to trip details table

Revision ID: d1b2e035b30c
Revises: 13e2e9b2e004
Create Date: 2026-06-03 13:10:57.676881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b2e035b30c'
down_revision: Union[str, Sequence[str], None] = '13e2e9b2e004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripdetails', sa.Column('trip_start_date', sa.DateTime(), nullable=False))
    op.add_column('tripdetails', sa.Column('expected_return_date', sa.DateTime(), nullable=False))
    op.add_column('tripdetails', sa.Column('actual_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripdetails', 'actual_end_date')
    op.drop_column('tripdetails', 'expected_return_date')
    op.drop_column('tripdetails', 'trip_start_date')
    # ### end Alembic commands ###
